### PR TITLE
Tokenizer, clitics- and tokenization-related fixes (replaces #89)

### LINKED ISSUE #69: create StextualDS.tokenize()
create method tokenize() for STextualDs for a fast access.

### LINKED ISSUE #86: Tokenizer sets Italian (?) clitics to LanguageCode for Spanish
Cf. https://github.com/korpling/salt/blob/3fe7e613a9ff52a00e57b33cef2a17da6a724f95/salt-api/src/main/java/org/corpus_tools/salt/common/tokenizer/Tokenizer.java#L333-L334

I'm not a speaker of Italian, but I do know a little Spanish. I've never seen any of the clitics above in Spanish, but am sure I've seen at least some of them on menus in pizzerias :wink:.

### LINKED ISSUE #87: Proclitics regex for French doesn't work as expected
For tokens like "qu'il", the [regex](https://github.com/korpling/salt/blob/3fe7e613a9ff52a00e57b33cef2a17da6a724f95/salt-api/src/main/java/org/corpus_tools/salt/common/tokenizer/Tokenizer.java#L331) will produce unexpected groups 1 and 2, which will both be "qu'". This breaks the tokenization. I imagine this is because you get the "qu'" expression more than once in the regex, but am not an expert.

### PR DESCRIPTION
**Pull request by thomaskrause**
- Fix #69
- Fix #86
- Fix #87
- Add dynamic clitics support, i.e., the ability to set proclitics and enclitics on a specific language (referenced by LanguageCode) in Tokenizer, similar to how abbreviations work.
- Add tests

### CODE REVIEW

File: salt-api/src/main/java/org/corpus_tools/salt/common/tokenizer/Clitics.java [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+	// character sequences which have to be cut off at the beginning of a word
+	private String proclitic = "";
+
+	// character sequences which have to be cut off at the end of a word
+	private String enclitic = "";
+
+	public String getProclitic() {
+		return proclitic;
+	}
+	public Clitics setProclitic(String pClitic) {
```
Comment (thomaskrause) [inline salt-api/src/main/java/org/corpus_tools/salt/common/tokenizer/Clitics.java]: Maybe it's better if the constructor takes the values for proclitic and enclititc pattern as arguments instead of using setter function.  The private variables would be  final then and a `Clititcs` object would be immutable.

File: salt-api/src/main/java/org/corpus_tools/salt/common/tokenizer/Tokenizer.java [hunk 2]
```diff
@@ -584,26 +638,32 @@ private void setClitics(LanguageCode language) {
...
-			m = p.matcher(lstTokens.get(i));
-			if (m.find() && !FClitic.isEmpty()) {
-				lstTokens.remove(i);
-				lstTokens.add(i, m.group(2));
-				lstTokens.add(i, m.group(1));
-				i++; // next token is a known enclitic, skip it
-				continue; // advance to get past the enclitic
-			}
+				if (getClitics(language) != null && getClitics(language).getEnclitic() != null) {
+				p = Pattern.compile("(.+)" + getClitics(language).getEnclitic() + "$");
```
Comment (thomaskrause) [inline salt-api/src/main/java/org/corpus_tools/salt/common/tokenizer/Tokenizer.java]: indentation seems wrong

File: salt-api/src/main/java/org/corpus_tools/salt/common/tokenizer/Tokenizer.java [hunk 3]
```diff
@@ -584,26 +638,32 @@ private void setClitics(LanguageCode language) {
...
+				m = p.matcher(lstTokens.get(i));
+				if (m.find() && (!getClitics(language).getEnclitic().isEmpty())) {
```
Comment (thomaskrause) [inline salt-api/src/main/java/org/corpus_tools/salt/common/tokenizer/Tokenizer.java]: You use `getClitics(language).getEnclitic()` three times in this block. It would be better to cache the returned object instead of accessing the clitics map all the time.

**Comment by thomaskrause** [comment]
Can you also update the CHANGELOG.txt with links to the tickets/issues in Github that are solved?
